"""add_forecast_dedup_unique_constraint

Revision ID: 6d75472ec153
Revises: 596375fe5d4e
Create Date: 2026-03-16 08:45:47.260088+00:00
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6d75472ec153'
down_revision: str | None = '596375fe5d4e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_forecast_dedup', 'weather_forecasts', ['source', 'city_id', 'forecast_date', 'issued_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_forecast_dedup', 'weather_forecasts', type_='unique')
    # ### end Alembic commands ###
