"""initial schema - all 13 tables

Revision ID: 596375fe5d4e
Revises: 
Create Date: 2026-03-16 04:11:03.847321+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '596375fe5d4e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kalshi_ticker_prefix', sa.String(length=10), nullable=False),
    sa.Column('nws_station_id', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kalshi_ticker_prefix'),
    sa.UniqueConstraint('nws_station_id')
    )
    op.create_table('paper_portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('sizing_strategy', sa.Enum('FIXED_PCT', 'KELLY', 'CONFIDENCE_SCALED', name='sizing_strategy_enum', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role_enum', create_constraint=True), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('email_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_type', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kalshi_markets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('market_id', sa.String(length=100), nullable=False),
    sa.Column('ticker', sa.String(length=100), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('forecast_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_type', sa.Enum('HIGH', 'LOW', name='market_type_enum', create_constraint=True), nullable=False),
    sa.Column('bracket_low', sa.Float(), nullable=True),
    sa.Column('bracket_high', sa.Float(), nullable=True),
    sa.Column('is_edge_bracket', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'SETTLED', name='market_status_enum', create_constraint=True), nullable=False),
    sa.Column('settlement_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_index('ix_markets_city_date', 'kalshi_markets', ['city_id', 'forecast_date'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('forecast_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_type', sa.Enum('HIGH', 'LOW', name='market_type_enum', create_constraint=True), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('predicted_temp', sa.Float(), nullable=False),
    sa.Column('std_dev', sa.Float(), nullable=False),
    sa.Column('probability_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('weather_forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('forecast_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temp_high', sa.Float(), nullable=True),
    sa.Column('temp_low', sa.Float(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forecasts_city_date_source', 'weather_forecasts', ['city_id', 'forecast_date', 'source', 'issued_at'], unique=False)
    op.create_index('ix_forecasts_source', 'weather_forecasts', ['source'], unique=False)
    op.create_table('kalshi_market_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('yes_bid', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('yes_ask', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('no_bid', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('no_ask', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['kalshi_markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshots_market_time', 'kalshi_market_snapshots', ['market_id', 'timestamp'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('BUY_YES', 'BUY_NO', name='direction_enum', create_constraint=True), nullable=False),
    sa.Column('model_probability', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('kalshi_probability', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('gap', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['kalshi_markets.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendations_created', 'recommendations', ['created_at'], unique=False)
    op.create_table('user_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('BUY_YES', 'BUY_NO', name='direction_enum', create_constraint=True), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('contracts_qty', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settlement_outcome', sa.Enum('WIN', 'LOSS', name='settlement_outcome_enum', create_constraint=True), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['kalshi_markets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_log_recommendations',
    sa.Column('email_log_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['email_log_id'], ['email_logs.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('email_log_id', 'recommendation_id')
    )
    op.create_table('paper_trades_fixed',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('contracts_qty', sa.Integer(), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settlement_outcome', sa.Enum('WIN', 'LOSS', name='settlement_outcome_enum', create_constraint=True), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id')
    )
    op.create_index('ix_paper_fixed_unsettled', 'paper_trades_fixed', ['settled_at'], unique=False)
    op.create_table('paper_trades_portfolio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('contracts_qty', sa.Integer(), nullable=False),
    sa.Column('position_size_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settlement_outcome', sa.Enum('WIN', 'LOSS', name='settlement_outcome_enum', create_constraint=True), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['paper_portfolios.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_portfolio_unsettled', 'paper_trades_portfolio', ['settled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paper_portfolio_unsettled', table_name='paper_trades_portfolio')
    op.drop_table('paper_trades_portfolio')
    op.drop_index('ix_paper_fixed_unsettled', table_name='paper_trades_fixed')
    op.drop_table('paper_trades_fixed')
    op.drop_table('email_log_recommendations')
    op.drop_table('user_trades')
    op.drop_index('ix_recommendations_created', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_snapshots_market_time', table_name='kalshi_market_snapshots')
    op.drop_table('kalshi_market_snapshots')
    op.drop_index('ix_forecasts_source', table_name='weather_forecasts')
    op.drop_index('ix_forecasts_city_date_source', table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    op.drop_table('refresh_tokens')
    op.drop_table('predictions')
    op.drop_index('ix_markets_city_date', table_name='kalshi_markets')
    op.drop_table('kalshi_markets')
    op.drop_table('email_logs')
    op.drop_table('users')
    op.drop_table('paper_portfolios')
    op.drop_table('cities')
    # ### end Alembic commands ###
